# Generated by Django 4.2.7 on 2023-12-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_cooking_steps_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_steps',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
